### ISSUE TITLE
Code for the models

### ISSUE THREAD

**Issue by hypnopump** [Coderx7/SimpleNet#1]
Hey, first of all, congrats on the good results you're showing. I was wondering if I could see the code for implementing the architectures. I've found some .caffemodel files, but not a .py file with the model architecture implementation in order to see if you've implemented some kind of preprocessing, normalization on so on.

Could you please provide those files?

**Comment by Coderx7** [comment]
@EricAlcaide  : Hi, Thanks, you can see and access the model definitions in prototxt format from [Models](https://github.com/Coderx7/SimpleNet/tree/master/SimpNet_V1/Models)  
In Caffe unlike TF or Pytorch, we mostly use prototxt files rather than implementing the architecture through the python wrapper. 
As I explained in the paper, I used normalization and zero padding the input (for CIFAR10/100). 
The same preprocessing which was used by stochastic-depth paper, you can access the script from [here](https://github.com/Pastromhaug/caffe-stochastic-depth/blob/master/examples/cifar10/preprocessing.py)
